name: Continuous Integration Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Api
        run: dotnet build "Api/.NET API.csproj" --no-restore --configuration Release

      - name: Build UnitTest
        run: dotnet build "UnitTest/UnitTest.csproj" --no-restore --configuration Release
